---
# We use a job that is indexed to get a reliable hostname for the registry!
apiVersion: batch/v1
kind: Job
metadata:
  name: registry
spec:
  completions: 1
  parallelism: 1
  completionMode: Indexed
  template:
    metadata:
      labels:
        # This selector label is for the job
        app: registry

        # This is for the node service
        service: registry
        name: registry
    spec:
      restartPolicy: OnFailure
      # This needs to match the service
      subdomain: r
      # TODO could use init containers for some kind of certificate
      # see https://kubernetes.io/docs/tasks/job/indexed-parallel-processing-static/
      containers:
      - name: registry
        image: registry:2
        env:
        - name: REGISTRY_HTTP_SECRET
          value: notsosecret
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  # This is superficially set to be short because of DNS name limit
  name: r
spec:
  selector:
    app: registry
  clusterIP: None
  ports:
    - port: 5000
      targetPort: 5000