name: test-googlebatch-true-api

on:
  workflow_dispatch:

jobs:
  testing-true-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11' 

      - name: Install poetry
        run: pip install poetry

      - name: Determine dependencies
        run: poetry lock

      - name: Install dependencies
        run: poetry install

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
  
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
  
      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Run pytest
        run: |
          poetry run pytest tests/tests_true_api.py -v